@baseurl = http://localhost:3000

###
POST {{baseurl}}/ciclista
Content-Type: application/json

{
  "ciclista": {
    "nome": "string",
    "nascimento": "2024-11-30",
    "cpf": "78830917946",
    "passaporte": {
      "numero": "string",
      "validade": "2024-11-30",
      "pais": "WJ"
    },
    "nacionalidade": "string",
    "email": "user@example.com",
    "urlFotoDocumento": "string",
    "senha": "string"
  },
  "meioDePagamento": {
    "nomeTitular": "string",
    "numero": "1234123412341234",
    "validade": "2024-11-30",
    "cvv": "1270"
  }
}
###
GET {{baseurl}}/ciclista/existeEmail/user@example.com

###
POST {{baseurl}}/ciclista/1/ativar

###
GET {{baseurl}}/cartaoDeCredito/1

###
POST {{baseurl}}/funcionario
Content-Type: application/json

{
  "senha": "string",
  "confirmacaoSenha": "string",
  "email": "user@example.com",
  "nome": "string",
  "idade": 0,
  "funcao": "string",
  "cpf": "string"
}

###
DELETE {{baseurl}}/funcionario/1
